language: go

go:
  - "1.10"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_script:
  - sudo service mysql stop
  - docker pull mysql:5.7

branches:
  only:
    - develop

jobs:
  include:
    - stage: Unit Test
      script: make test
    - stage: Release
      if: tag =~ ^v
      env: REV="$TRAVIS_TAG"
      deploy:
        provider: releases
        skip_cleanup: true
        on:
          tags: true
