language: go

go:
  - "1.10"

services:
- docker
- mysql

addons:
  apt:
    packages:
      - docker-ce

before_script:
  - make deps

branches:
  only:
    - master

jobs:
  include:
    - stage: Host MySQL Test
      script:
      - TEST_MYSQL_HOST=127.0.0.1 TEST_MYSQL_PORT=3306 TEST_MYSQL_PASSWORD="" go test ./test
    - stage: Unit Test
      script:
      - make test
    - stage: Release
      if: tag =~ ^v
      env: REV="$TRAVIS_TAG"
      deploy:
        provider: releases
        skip_cleanup: true
        on:
          tags: true
